# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chat Confidential
email: murdock@ualberta.ca
description: > # this means to ignore newlines until "baseurl:"
  Chat Confidential is an anonymous messaging platform with applications in hospital
  and counselling settings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seannmurdock.github.io" # the base hostname & protocol for your site
github_username:  SeannMurdock

# Build settings
markdown: kramdown
